version: '2' 
services:
  battlefrank:
    image: fake-backend:latest
    ports:
      - "8181:3000"
    links:
      - dbfrank
    volumes:
      - ./static_files:/etc/backend/static
    restart: always
    environment:
      - DATABASE_HOST=dbfrank
      - DATABASE_PORT=3306
      - DATABASE_USER=battleuser
      - DATABASE_PASSWORD=battlepass
      - DATABASE_NAME=battleboat
  dbfrank:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwdfrank
      - MYSQL_DATABASE=battleboat
      - MYSQL_USER=battleuser
      - MYSQL_PASSWORD=battlepass
    restart: always
    volumes:
      - mysql_config:/var/lib/mysql 
volumes:
  mysql_config:
